<?php
if ($generate) {
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Exemple d'auto génération de PDF</title>
</head>
<body>
<?php
}
?>
<br>
Ceci est un exemple de génération de PDF via un bouton :)<br>
<br>
<img src="<?php echo $url ?>" alt="image_php"><br>
<br>
<?php
if ($generate) {
    ?>
    Bonjour <b><?php echo $nom; ?></b>, ton nom peut s'écrire : <br>
    <barcode type="C39" value="<?php echo strtoupper($nom); ?>" style="color: #770000"></barcode>
    <hr>
    <br>
    <?php
}
?>
<br>
<?php
if (!$generate) {
    ?>


    <form method="get" action="">
        <input type="hidden" name="make_pdf" value="">
        Ton nom : <input type="text" name="nom" value=""> -
        <input type="submit" value="Generer le PDF">
    </form>
    <?php
}
?>
</body>
</html>


